### ISSUE TITLE
Has the exposure_time attribute of HMI maps always been equal to None?

### ISSUE THREAD

**Issue by byrdie** [Kankelborg-Group/kgpy#2]
@jacobdparker, I'm trying to fix the last test in `kgpy.observatories.sdo.hmi`.

According to this [error log](https://github.com/Kankelborg-Group/kgpy/runs/5491985601?check_suite_focus=true#step:7:497) after we create a `sunpy.map.Map` instance of some HMI data, the `exposure_time` attribute is `None`.

Do you know if this has always been this way, or is this a regression in `sunpy.map.Map`? I would've expected it to be 45 seconds or something.

**Comment by jacobdparker** [comment]
I don't know if it has always been that way
______________________________________
Jake Parker
